### ISSUE TITLE
Problem with row and column offsets

### ISSUE THREAD

**Issue by beardyw** [LongHairedHacker/avr-st7735#2] opened 2019-04-27 13:06 UTC
Thanks for this code, it is working well for me.

But when working with ST7735_RED_18_GREENTAB in landscape mode and doing a full screen st7735_fill_rect I was getting an unfilled single pixel border down the left and bottom sides of the screen.

I tracked that down to the fact that the column and border offsets are not being swapped in landscape mode.

**Comment by LongHairedHacker** [comment] 2019-05-08 07:26
Thanks a lot. 

Unfortunately I don't have a display of that type, so I can't reproduce the bug or test the fix.
However if you can provide me with the fixed part of the code, or event better a pull-request, I'll be happy to merge it.

**Comment by beardyw** [comment] 2019-05-08 09:43
I've used git but never done a pull request - it will be a learning
experience for me. Bear with me.

Steve

**Comment by LongHairedHacker** [comment] 2019-05-09 13:59
No problem.

Take your time and don't hesitate to ask if you get stuck somewhere.

**Comment by LongHairedHacker** [comment] 2019-06-01 18:48
#3 is merged now, so I guess this can be closed.

**Closed as completed** 2019-06-07 13:13 UTC
